# Generated by Django 3.2.5 on 2023-01-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=200)),
                ('klasse', models.IntegerField()),
                ('schule', models.CharField(max_length=200)),
                ('lehrer_mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
