# Generated by Django 3.2.5 on 2023-02-21 13:40

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    replaces = [('mathesdigi_app', '0001_initial'), ('mathesdigi_app', '0002_auto_20230201_2003'), ('mathesdigi_app', '0003_auto_20230203_0926'), ('mathesdigi_app', '0004_auto_20230203_2002'), ('mathesdigi_app', '0005_alter_user_pub_date'), ('mathesdigi_app', '0006_alter_user_pub_date'), ('mathesdigi_app', '0007_auto_20230220_2039'), ('mathesdigi_app', '0008_auto_20230221_1436')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aufgaben',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aufgaben_nr', models.IntegerField()),
                ('heft_nr', models.IntegerField()),
                ('bezeichnung', models.CharField(max_length=200)),
                ('punktzahl', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Aufgabe',
                'verbose_name_plural': 'Aufgaben',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=254)),
                ('heft', models.CharField(default=2, max_length=50)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2023, 2, 21, 13, 36, 18, 462635, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Teilaufgaben',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teilaufgaben_id', models.CharField(max_length=5)),
                ('loesung', models.CharField(max_length=20)),
                ('aufgabe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathesdigi_app.aufgaben')),
            ],
            options={
                'verbose_name': 'Teilaufgabe',
                'verbose_name_plural': 'Teilaufgaben',
            },
        ),
        migrations.CreateModel(
            name='Wertung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heft_nr', models.IntegerField()),
                ('rohwert', models.IntegerField()),
                ('t_wert', models.CharField(max_length=4)),
                ('prozentrang', models.IntegerField()),
                ('end_month', models.IntegerField(default=2)),
                ('start_month', models.IntegerField(default=2)),
                ('end_day', models.IntegerField(default=2)),
                ('start_day', models.IntegerField(default=2)),
            ],
            options={
                'verbose_name': 'Wertung',
                'verbose_name_plural': 'Wertungen',
            },
        ),
        migrations.CreateModel(
            name='Ergebnisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eingabe', models.CharField(max_length=200, null=True)),
                ('wertung', models.BooleanField(null=True)),
                ('teilaufgabe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathesdigi_app.teilaufgaben')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathesdigi_app.user')),
                ('time_required', models.IntegerField(default=None, null=True)),
            ],
            options={
                'verbose_name': 'Ergebnis',
                'verbose_name_plural': 'Ergebnisse',
            },
        ),
    ]
