# Generated by Django 3.2.5 on 2023-02-01 19:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mathesdigi_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aufgaben',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aufgaben_nr', models.IntegerField()),
                ('heft_nr', models.IntegerField()),
                ('bezeichnung', models.CharField(max_length=200)),
                ('punktzahl', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Aufgabe',
                'verbose_name_plural': 'Aufgaben',
            },
        ),
        migrations.CreateModel(
            name='Wertung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heft_nr', models.IntegerField()),
                ('rohwert', models.IntegerField()),
                ('t_wert', models.CharField(max_length=4)),
                ('prozentrang', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Wertung',
                'verbose_name_plural': 'Wertungen',
            },
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lehrer_mail',
            new_name='mail',
        ),
        migrations.RemoveField(
            model_name='user',
            name='klasse',
        ),
        migrations.RemoveField(
            model_name='user',
            name='schule',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.AddField(
            model_name='user',
            name='heft',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 1, 19, 3, 28, 644343, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Teilaufgaben',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teilaufgaben_id', models.CharField(max_length=5)),
                ('loesung', models.IntegerField()),
                ('aufgabe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathesdigi_app.aufgaben')),
            ],
            options={
                'verbose_name': 'Teilaufgabe',
                'verbose_name_plural': 'Teilaufgaben',
            },
        ),
        migrations.CreateModel(
            name='Ergebnisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eingabe', models.CharField(max_length=200, null=True)),
                ('wertung', models.BooleanField(null=True)),
                ('teilaufgabe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathesdigi_app.teilaufgaben')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathesdigi_app.user')),
            ],
            options={
                'verbose_name': 'Ergebnis',
                'verbose_name_plural': 'Ergebnisse',
            },
        ),
    ]
