# Generated by Django 3.2.5 on 2023-01-21 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathesdigi_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jahrgang',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='pseudonym',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 21, 18, 42, 33, 259209)),
        ),
    ]
