# Generated by Django 3.2.5 on 2023-02-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathesdigi_app', '0002_auto_20230221_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wertung',
            name='end_day',
        ),
        migrations.RemoveField(
            model_name='wertung',
            name='end_month',
        ),
        migrations.RemoveField(
            model_name='wertung',
            name='start_day',
        ),
        migrations.RemoveField(
            model_name='wertung',
            name='start_month',
        ),
        migrations.AddField(
            model_name='wertung',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='wertung',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
