# Generated by Django 3.2.5 on 2023-01-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathesdigi_app', '0002_auto_20230121_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
