# Generated by Django 3.2.5 on 2023-02-23 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mathesdigi_app', '0003_auto_20230222_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ergebnisse',
            name='teilaufgabe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ergebnisse', to='mathesdigi_app.teilaufgaben'),
        ),
        migrations.AlterField(
            model_name='teilaufgaben',
            name='aufgabe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teilaufgaben', to='mathesdigi_app.aufgaben'),
        ),
    ]
