# Generated by Django 3.2.5 on 2023-01-22 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathesdigi_app', '0003_alter_user_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pseudonym',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
    ]
