# Generated by Django 3.2.5 on 2023-02-03 19:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mathesdigi_app', '0003_auto_20230203_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='wertung',
            name='end_day',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wertung',
            name='start_day',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 3, 19, 2, 7, 762023, tzinfo=utc)),
        ),
    ]
