# Generated by Django 3.2.5 on 2023-02-20 12:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mathesdigi_app', '0004_auto_20230203_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 20, 12, 35, 17, 982470, tzinfo=utc)),
        ),
    ]
