# Generated by Django 3.2.5 on 2023-01-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathesdigi_app', '0004_auto_20230122_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='lehrer_mail',
            new_name='mail',
        ),
        migrations.RemoveField(
            model_name='user',
            name='jahrgang',
        ),
        migrations.AddField(
            model_name='user',
            name='heft_nr',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
