# Generated by Django 3.2.5 on 2023-02-20 12:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mathesdigi_app', '0005_alter_user_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 20, 12, 37, 51, 485654, tzinfo=utc)),
        ),
    ]
