# Generated by Django 3.2.5 on 2023-01-22 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathesdigi_app', '0005_auto_20230122_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='heft_nr',
        ),
        migrations.RemoveField(
            model_name='user',
            name='klasse',
        ),
        migrations.RemoveField(
            model_name='user',
            name='schule',
        ),
    ]
