# Generated by Django 3.2.5 on 2023-01-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathesdigi_app', '0008_aufgaben_ergebnisse_teilaufgaben'),
    ]

    operations = [
        migrations.AddField(
            model_name='teilaufgaben',
            name='loesung',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
