# Generated by Django 3.2.5 on 2023-01-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathesdigi_app', '0009_teilaufgaben_loesung'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='heft_nr',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
