# Generated by Django 3.2.5 on 2023-01-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathesdigi_app', '0011_auto_20230123_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ergebnisse',
            name='eingabe',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ergebnisse',
            name='wertung',
            field=models.BooleanField(null=True),
        ),
    ]
