# Generated by Django 3.2.5 on 2023-01-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathesdigi_app', '0012_auto_20230123_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aufgaben',
            options={'verbose_name': 'Aufgabe', 'verbose_name_plural': 'Aufgaben'},
        ),
        migrations.AlterModelOptions(
            name='ergebnisse',
            options={'verbose_name': 'Ergebnis', 'verbose_name_plural': 'Ergebnisse'},
        ),
        migrations.AlterModelOptions(
            name='teilaufgaben',
            options={'verbose_name': 'Teilaufgabe', 'verbose_name_plural': 'Teilaufgaben'},
        ),
        migrations.AddField(
            model_name='user',
            name='session_key',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
