# Generated by Django 3.2.5 on 2023-01-24 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathesdigi_app', '0013_auto_20230124_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='session_key',
        ),
    ]
